### ISSUE TITLE
Ask About encrypt

### ISSUE THREAD

**Issue by KCTechlead** [Open-Attestation/schemata#7]
Hi all,

I want to ask about encrypt and decrypt document. I've create a health cert wrap document using health cert schema and then encrypt it like opencerts demo by following this link https://openattestation.com/docs/component/open-attestation.
but after redirect to dev.opencerts.io error invalid parameter but if I change the url format like tradetrust document is no problem.

may the encrypt and decrpyt only for opencerts demo or all document. if all document may I know what a mistake from me

thanks

**Comment by Nebulis** [comment]
What's the url ?

**Comment by KCTechlead** [comment]
this url without encrypt
https://action.openattestation.com?q={"type":"DOCUMENT","payload":{"uri":"https://test-api.knowledgecatalyst.io/encrypt/health-document/1d78d750-4363-4a24-9f2c-642a7292602a","permittedActions":["STORE"],"redirect":"https://dev.opencerts.io"}}

this url with encrypt
https://action.openattestation.com?q={"type":"DOCUMENT","payload":{"uri":"https://test-api.knowledgecatalyst.io/encrypt/health-document/ca014caa-541f-4867-a2ba-88d42c375858","key":"fd91e4b1663cc7455f54bc0d38d10161331b50a34f0515a0377d93cbfc311252","permittedActions":["STORE"],"redirect":"https://dev.opencerts.io"}}

**Comment by Nebulis** [comment]
Both links works on my side, the difference is that the second link doesn't render because the renderer URL is invalid:

![image](https://user-images.githubusercontent.com/503185/98641228-626ed880-2366-11eb-88e3-984950ef73fe.png)

**Comment by KCTechlead** [comment]
yes now is working, I don't know yesterday is always invalid parameter. Ok thanks, but are there any examples of url templates apart from the ones govtech-renderer.openattestation.com ?

**Comment by Nebulis** [comment]
URL templates for doing what ? We have some deployed templates (like govtech-renderer.openattestation.com). I used this one for the healthcert example because I know there is a fallback renderer and no official renderer for healthcert yet

**Comment by KCTechlead** [comment]
ah ok thanks
